### PR TITLE
Upgrade to Decidim v0.23

### PR DESCRIPTION
**Pull request by Leusev**
Upgrade Decidim version to release/0.23-stable. 
Upgrade notes: https://github.com/decidim/decidim/blob/release/0.23-stable/CHANGELOG.md

### Tasks
- [x] Run migrations
- [x] Update decidim version

### CODE REVIEW

**Review by victorol1 — COMMENTED** [review]
Hi @Leusev, I've changed the base branch to master since 0.22 is already merged, solve the conflicts when u get a chance please

**Comment by Leusev** [comment]
Done @victorol1 ! :smile:

**Review by tramuntanal — APPROVED** [review]
LGTM @Leusev

**Comment by tramuntanal** [comment]
Remember that there are serveral upgrade notes: minimum Ruby version to 2.6.6, new syntax for Geocoder configuration, etc..

**Comment by tramuntanal** [comment]
Ok @Leusev Remember to create the new Here maps key and run
```
  Decidim::Comments::Comment.find_each(&:try_update_index_for_search_resource)
  Decidim::Debates::Debate.find_each(&:try_update_index_for_search_resource)
```
after deployment

**Pull request merged**
